In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv(r"/content/final_df.csv")
df.sample(10)

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,european_aqi,temperature_2m,relative_humidity_2m,wind_speed_10m,pressure_msl,precipitation
17360,2024-12-24 08:00:00,41.9,45.4,490.0,14.8,20.1,119.0,110,16.8,38,7.7,1018.3,0.0
23180,2025-08-23 20:00:00,36.7,37.5,420.0,23.0,4.7,69.0,69,23.7,88,9.3,1002.6,0.1
24099,2025-10-01 03:00:00,30.9,33.1,1744.0,43.7,10.5,66.0,66,20.7,89,9.6,1007.2,0.8
15889,2024-10-24 01:00:00,25.3,44.7,874.0,33.5,3.3,10.0,78,17.7,67,10.1,1014.4,0.0
9001,2024-01-11 01:00:00,21.1,31.9,951.0,31.7,4.8,22.0,81,7.8,65,4.4,1018.2,0.0
381,2023-01-16 21:00:00,75.4,109.9,1147.0,23.9,12.1,67.0,93,5.5,70,8.7,1017.5,0.0
24884,2025-11-02 20:00:00,43.1,44.2,661.0,62.8,7.0,25.0,75,17.3,59,1.9,1011.7,0.0
8884,2024-01-06 04:00:00,53.0,81.3,1921.0,46.8,12.5,32.0,92,8.5,67,2.3,1022.6,0.0
8529,2023-12-22 09:00:00,25.0,36.3,668.0,29.8,15.7,89.0,67,18.7,43,8.6,1016.1,0.0
5958,2023-09-06 06:00:00,27.2,50.8,409.0,7.3,23.0,190.0,71,32.2,47,2.7,1007.9,0.0

In [5]:
#lets chcek the null and duplicate values in the data

In [6]:
df.isnull().sum()

time                    0
pm2_5                   0
pm10                    0
carbon_monoxide         0
nitrogen_dioxide        0
sulphur_dioxide         0
ozone                   0
european_aqi            0
temperature_2m          0
relative_humidity_2m    0
wind_speed_10m          0
pressure_msl            0
precipitation           0
dtype: int64

In [7]:
#check the types of the columns
df.dtypes

time                     object
pm2_5                   float64
pm10                    float64
carbon_monoxide         float64
nitrogen_dioxide        float64
sulphur_dioxide         float64
ozone                   float64
european_aqi              int64
temperature_2m          float64
relative_humidity_2m      int64
wind_speed_10m          float64
pressure_msl            float64
precipitation           float64
dtype: object

In [15]:
#check the duplicates rows
df.duplicated().sum()

np.int64(0)

In [16]:
df = df.sort_values("time").reset_index(drop=True)

In [17]:
df.isnull().sum()

time                    0
pm2_5                   0
pm10                    0
carbon_monoxide         0
nitrogen_dioxide        0
sulphur_dioxide         0
ozone                   0
european_aqi            0
temperature_2m          0
relative_humidity_2m    0
wind_speed_10m          0
pressure_msl            0
precipitation           0
dtype: int64

In [18]:
df["pm2_5_roll_3h"] = df["pm2_5"].rolling(window=3).mean()
df["pm2_5_std_3h"] = df["pm2_5"].rolling(window=3).std()

In [19]:
df["pm2_5_roll_6h"] = df["pm2_5"].rolling(window=6).mean()
df["pm2_5_std_6h"] = df["pm2_5"].rolling(window=6).std()

In [20]:
df["pm2_5_roll_24h"] = df["pm2_5"].rolling(window=24).mean()
df["pm2_5_std_24h"] = df["pm2_5"].rolling(window=24).std()

In [23]:
df.isnull().sum()

time                     0
pm2_5                    0
pm10                     0
carbon_monoxide          0
nitrogen_dioxide         0
sulphur_dioxide          0
ozone                    0
european_aqi             0
temperature_2m           0
relative_humidity_2m     0
wind_speed_10m           0
pressure_msl             0
precipitation            0
pm2_5_roll_3h            2
pm2_5_std_3h             2
pm2_5_roll_6h            5
pm2_5_std_6h             5
pm2_5_roll_24h          23
pm2_5_std_24h           23
dtype: int64

In [24]:
df = df.dropna()

In [25]:
df.isnull().sum()

time                    0
pm2_5                   0
pm10                    0
carbon_monoxide         0
nitrogen_dioxide        0
sulphur_dioxide         0
ozone                   0
european_aqi            0
temperature_2m          0
relative_humidity_2m    0
wind_speed_10m          0
pressure_msl            0
precipitation           0
pm2_5_roll_3h           0
pm2_5_std_3h            0
pm2_5_roll_6h           0
pm2_5_std_6h            0
pm2_5_roll_24h          0
pm2_5_std_24h           0
dtype: int64

In [26]:
df.shape

(30409, 19)

In [27]:
df.columns

Index(['time', 'pm2_5', 'pm10', 'carbon_monoxide', 'nitrogen_dioxide',
       'sulphur_dioxide', 'ozone', 'european_aqi', 'temperature_2m',
       'relative_humidity_2m', 'wind_speed_10m', 'pressure_msl',
       'precipitation', 'pm2_5_roll_3h', 'pm2_5_std_3h', 'pm2_5_roll_6h',
       'pm2_5_std_6h', 'pm2_5_roll_24h', 'pm2_5_std_24h'],
      dtype='object')

In [28]:
rename_dict = {
    'time': 'Timestamp',
    'pm2_5': 'PM2.5',
    'pm10': 'PM10',
    'carbon_monoxide': 'Carbon_Monoxide_CO',
    'nitrogen_dioxide': 'Nitrogen_Dioxide_NO2',
    'sulphur_dioxide': 'Sulphur_Dioxide_SO2',
    'ozone': 'Ozone_O3',
    'european_aqi': 'European_AQI',
    'temperature_2m': 'Temperature',
    'relative_humidity_2m': 'Humidity',
    'wind_speed_10m': 'Wind_Speed',
    'pressure_msl': 'Air_Pressure',
    'precipitation': 'Rainfall',
    'pm2_5_roll_3h': 'PM2.5_3h_Mean',
    'pm2_5_std_3h': 'PM2.5_3h_Std',
    'pm2_5_roll_6h': 'PM2.5_6h_Mean',
    'pm2_5_std_6h': 'PM2.5_6h_Std',
    'pm2_5_roll_24h': 'PM2.5_24h_Mean',
    'pm2_5_std_24h': 'PM2.5_24h_Std'
}

df.rename(columns=rename_dict, inplace=True)
print(df.columns)

Index(['Timestamp', 'PM2.5', 'PM10', 'Carbon_Monoxide_CO',
       'Nitrogen_Dioxide_NO2', 'Sulphur_Dioxide_SO2', 'Ozone_O3',
       'European_AQI', 'Temperature', 'Humidity', 'Wind_Speed', 'Air_Pressure',
       'Rainfall', 'PM2.5_3h_Mean', 'PM2.5_3h_Std', 'PM2.5_6h_Mean',
       'PM2.5_6h_Std', 'PM2.5_24h_Mean', 'PM2.5_24h_Std'],
      dtype='object')

In [29]:
df.to_csv("Preprocess_Weather_data.csv",index=False)